const CREATE_COLUMNS = {
    first_name: null,
    middle_name: null,
    last_name: null,
    title: null,
    company_name: null,
    email: null,
    phone_number: null,
    website: null,
    notes: null,
    address_line1: null,
    address_line2: null,
    city: null,
    state: null,
    postal_code: null,
    country: null,
    billing_address_line1: null,
    billing_address_line2: null,
    billing_city: null,
    billing_state: null,
    billing_postal_code: null,
    billing_country: null,
}
const MIN_LENGTH = {
    FIRST_NAME: 1,
    MIDDLE_NAME: 0,
    LAST_NAME: 1,
    TITLE: 0,
    COMPANY_NAME: 1,
    EMAIL: 1,
    PHONE: 0,
    WEBSITE: 0,
    NOTES: 0,
    ADDRESS_LINE: 0,
    CITY: 0,
    STATE: 0,
    ZIP: 0,
    COUNTRY: 0,
}
const MAX_LENGTH = {
    FIRST_NAME: 100,
    MIDDLE_NAME: 100,
    LAST_NAME: 100,
    TITLE: 100,
    COMPANY_NAME: 255,
    EMAIL: 255,
    PHONE: 20,
    WEBSITE: 255,
    NOTES: 5000,
    ADDRESS_LINE: 255,
    CITY: 100,
    STATE: 100,
    ZIP: 20,
    COUNTRY: 100,
}

module.exports = { CREATE_COLUMNS, MIN_LENGTH, MAX_LENGTH };