const MIN_LENGTH = {
    EMPLOYEE_ID: 0,
    MANAGER_ID: 0,
    FIRST_NAME: 1,
    MIDDLE_NAME: 0,
    LAST_NAME: 1,
    DISPLAY_NAME: 0,
    TITLE: 0,
    COMPANY: 0,
    DEPARTMENT: 0,
    LOCATION: 0,
    STATUS: 0,
    EMAIL: 1,
    PHONE: 0,
    WEBSITE: 0,
    NOTES: 0,
    ADDRESS_LINE: 0,
    CITY: 0,
    STATE: 0,
    ZIP: 0,
    COUNTRY: 0,
    PASSWORD: 8,
}
const MAX_LENGTH = {
    EMPLOYEE_ID: 100,
    MANAGER_ID: 100,
    FIRST_NAME: 100,
    MIDDLE_NAME: 100,
    LAST_NAME: 100,
    DISPLAY_NAME: 100,
    TITLE: 100,
    COMPANY: 255,
    DEPARTMENT: 255,
    LOCATION: 255,
    STATUS: 100,
    EMAIL: 255,
    PHONE: 20,
    WEBSITE: 255,
    NOTES: 5000,
    ADDRESS_LINE: 255,
    CITY: 100,
    STATE: 100,
    ZIP: 20,
    COUNTRY: 100,
    PASSWORD: 255,
}
const ROLES = {
    MANAGER: 'Manager',
    EMPLOYEE: 'Employee',
}
const CREATED_COLUMNS = {
    EMPLOYEE_ID: 'employee_id',
    MANAGER_ID: 'manager_id',
    FIRST_NAME: 'first_name',
    MIDDLE_NAME: 'middle_name',
    LAST_NAME: 'last_name',
    DISPLAY_NAME: 'display_name',
    TITLE: 'title',
    COMPANY: 'company',
    DEPARTMENT: 'department',
    LOCATION: 'location',
    STATUS: 'status',
    EMAIL: 'email',
    PHONE_NUMBER: 'phone_number',
    WEBSITE: 'website',
    NOTES: 'notes',
    ADDRESS_LINE1: 'address_line1',
    ADDRESS_LINE2: 'address_line2',
    CITY: 'city',
    STATE: 'state',
    POSTAL_CODE: 'postal_code',
    COUNTRY: 'country',
    ROLE: 'account_role'
}
const UPDATED_COLUMNS = {
    PASSWORD_UPDATED: 'password_updated_at',
    PASSWORD_EXPIRES: 'password_expires_at',
    LAST_LOGIN: 'last_login',
    CREATED: 'created_at',
    UPDATED: 'updated_at',
    IS_ADMIN: 'is_admin',
    IS_ACTIVE: 'is_active',
}
const SECURE_COLUMNS = {
    PASSWORD: 'password_hash',
}
const SAFE_RETURN = `
    user_id,
    employee_id,
    manager_id,
    first_name,
    middle_name,
    last_name,
    display_name,
    title,
    company,
    department,
    location,
    status,
    email,
    phone_number,
    website,
    notes,
    address_line1,
    address_line2,
    city,
    state,
    postal_code,
    country,
    last_login,
    created_at,
    updated_at,
    account_role,
    is_admin,
    is_active`;

module.exports = {SAFE_RETURN,UPDATED_COLUMNS, SECURE_COLUMNS, CREATED_COLUMNS, MIN_LENGTH, MAX_LENGTH, ROLES};